apiVersion: v1
kind: Service
metadata:
  name: deal-service
spec:
  selector:
    app: deal-service
  type: NodePort
  ports:
    - name: http
      port: 8082
      nodePort: 30003


---

apiVersion: app/v1
kind: Deployment
metadata:
  name: deal-service
spec:
  selector:
    matchLabels:
      app: deal-service
  replicas: 1
  template:
    metadata:
      labels:
        app: deal-service
    spec:
      containers:
        - name: service
          image: pavlokoval737/deal-service
          ports:
            - name: http
              containerPort: 8082

---