apiVersion: v1
kind: Service
metadata:
  name: service-deals
spec:
  selector:
    app: service-deals
  type: NodePort
  ports:
    - name: http
      port: 8093
      nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deals
spec:
  selector:
    matchLabels:
      app: service-deals
  replicas: 1
  template:
    metadata:
      labels:
        app: service-deals
    spec:
      containers:
        - name: server
          image: pavlokoval737/service-deals
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8093

---