apiVersion: v1
kind: Service
metadata:
  name: service-cars
spec:
  selector:
    app: service-cars
  type: NodePort
  ports:
    - name: http
      port: 8091
      nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-cars
spec:
  selector:
    matchLabels:
      app: service-cars
  replicas: 1
  template:
    metadata:
      labels:
        app: service-cars
    spec:
      containers:
        - name: server
          image: pavlokoval737/service-cars
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8091

---