apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  selector:
    app: car-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30001


---

apiVersion: app/v1
kind: Deployment
metadata:
  name: car-service
spec:
  selector:
    matchLabels:
      app: car-service
  replicas: 1
  template:
    metadata:
      labels:
        app: car-service
    spec:
      containers:
        - name: service
          image: pavlokoval737/car-service
          ports:
            - name: http
              containerPort: 8080

---